# Generated by Django 3.2.12 on 2022-04-17 19:28

from django.db import migrations, models
import djongo.models.fields
import votes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Votos_std', djongo.models.fields.EmbeddedField(model_container=votes.models.Votos_std, model_form_class=votes.models.Votos_stdForm)),
                ('Votos_taiko', djongo.models.fields.EmbeddedField(model_container=votes.models.Votos_taiko, model_form_class=votes.models.Votos_taikoForm)),
                ('Votos_ctb', djongo.models.fields.EmbeddedField(model_container=votes.models.Votos_ctb, model_form_class=votes.models.Votos_ctbForm)),
                ('Votos_mania', djongo.models.fields.EmbeddedField(model_container=votes.models.Votos_mania, model_form_class=votes.models.Votos_maniaForm)),
                ('nickname', models.CharField(max_length=20)),
                ('id_osu_usuario', models.IntegerField()),
            ],
        ),
    ]
