# Generated by Django 4.0.4 on 2022-04-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='osu_id',
            field=models.IntegerField(default=None),
        ),
    ]
