# Generated by Django 4.0.4 on 2022-05-09 05:24

from django.db import migrations, models
import votes.managers


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('objects', votes.managers.PlayerOAuth2Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
