# Generated by Django 4.0.4 on 2022-04-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cover_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='nick',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='user_avatar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playervotes',
            name='avatar_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playervotes',
            name='nick',
            field=models.CharField(max_length=20),
        ),
    ]
